quiz={
    "quiz_name":[
        {
            "question":"What is your name 1",
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":True
                },
            ]
        },
        {
            "question":'''What is your name 2''',
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":True
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
        {
            "question":"What is your name 3",
            "option":[
                {
                    "value":"1",
                    "answer":True
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
        {
            "question":"What is your name 4",
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":True
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
    ],
    "MRI":[
        {
            "question":"Hello",
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
    ],
}