quiz={
    "quiz_name":[
        {
            "question":"What is your name",
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
        {
            "question":"What is your name 2",
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
        {
            "question":"What is your name 3",
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
        {
            "question":"What is your name 4",
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
    ],
    "quiz_name_2":[
        {
            "question":"Hello",
            "option":[
                {
                    "value":"1",
                    "answer":False
                },
                {
                    "value":"2",
                    "answer":False
                },
                {
                    "value":"3",
                    "answer":False
                },
                {
                    "value":"4",
                    "answer":False
                },
            ]
        },
    ],
}